fix: warn before overwriting projects
molgenis/molgenis-r-armadillo pull request #104
Opened 2023-11-30 09:30 UTC by SietsmaRJ

- Added feature to `armadillo.create_project` that will (by default) no longer overwrite existing projects if the name happens to be the same. This overwrite can be turned on. When overwrite is turned on, will always warn the user.
- Fixed linting

Closes #91

2024-04-03 11:03 UTC, timcadman commented
Taken a different approach than previous - rather than include a variable to specify what to do I've now added a menu for the user to choose. Seemed more user-friendly for me, and also means that we don't have to pass and argument determining this behaviour from other functions (e.g. make_view which I'm writing). Tell me if you disagree!

2024-04-09 06:45 UTC, marikaris requested changes
I like what you did with the menu. I ran into some issues because I'm a stupid user, so:
would it be possible to additionally also be able to select "y" for yes and "n" for no? Also the "Yes" and "No" are now case sensitive. It only works, if I capitalise them, so I would like to be able to say "yes" or "no" as well. 

The code coverage is also going down. I do understand why that is, tests for the menu are a bit useless. So I won't be very mad if you don't write tests for those lines, but could you take a look at this?
I found this here that might help with mocking the menu:
https://stackoverflow.com/questions/65740390/how-to-test-a-function-that-depends-on-a-menu-user-input
Doesn't seem too complicated, so if that works, I think it's worth writing the tests.

2024-04-11 06:30 UTC, marikaris reviewed
<img width="807" alt="Screenshot 2024-04-11 at 08 19 57" src="https://github.com/molgenis/molgenis-r-armadillo/assets/10075439/4cd88a31-f5ce-4f89-aec3-0d2b8a524174">
@timcadman When I select an invalid choice, I get this error. I'm not sure if I like it or not. I think I'd prefer it if the error is caught and a nice message appears, rather than an error. What do you think?

2024-04-11 08:06 UTC, marikaris approved these changes

2024-04-11 08:19 UTC, merged